#######################################################################
#######################################################################
###																																	###
### docker-compose-qbittorent.yaml																	###
### Edited on/by: 10/21/24 by Jacob Barnes												  ###
###																																	###
#######################################################################
#######################################################################

services:
  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorent
    network_mode: "container:gluetun"
    volumes: 
    
    environment:
      - PUID="${PUID:?error}"
      - GUID="${GUID:?error}"
      - TZ="${TIME_ZONE:?error}"
      - WEBUI_PORT="${QBIT_WEBUI:?error}"
    restart: unless-stopped

# Gluetun manages the ports for containers that use "service:glueten"  
# qBittorent should ALWAYS use a VPN or a secure connection / socks5 proxy / etc.
