#######################################################################
#######################################################################
###																																	###
### docker-compose-qbittorent.yaml																	###
### Edited on/by: 10/15/24 by Jacob Barnes												  ###
###																																	###
#######################################################################
#######################################################################

services:
  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorent
    network_mode: "service:gluetun"
    volumes: 
    
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
    restart: unless-stopped

# Gluetun manages the ports for containers that use "service:glueten"  

#   ports:
#			- 8200:8200				## qBittorent WebUI
#			- 6881:6881       ## qBittorent TCP Connection
