#######################################################################
#######################################################################
###																																	###
### docker-compose-readarr.yaml																			###
### Edited on/by: 10/15/24 by Jacob Barnes												  ###
###																																	###
#######################################################################
#######################################################################

services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: "container:gluetun"
    volumes:
    
    environment: 
      - PUID="${PUID:?error}"
      - GUID="${GUID:?error}"
      - TZ="${TIME_ZONE:?error}"
    restart: unless-stopped
      
# Gluetun manages the ports for containers that use "service:glueten"  

#   ports:
#     - 8787:8787
