#######################################################################
#######################################################################
###																																	###
### docker-compose-radarr.yaml																		  ###
### Edited on/by: 10/15/24 by Jacob Barnes												  ###
###																																	###
#######################################################################
#######################################################################

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:glueten"
    volumes:
    
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
    restart: unless-stopped
      
# Gluetun manages the ports for containers that use "service:glueten"  

#   ports:
#     - 7878:7878
