#######################################################################
#######################################################################
###																																	###
### docker-compose-qbittorent.yaml																	###
### Edited on/by: 10/15/24 by Jacob Barnes												  ###
###																																	###
#######################################################################
#######################################################################

services:
  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorent
    network_mode: "service:gluetun"
    volumes: 
    
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    restart: unless-stopped

# Gluetun manages the ports for containers that use "service:glueten"  
# qBittorent should ALWAYS use a VPN or a secure connection / socks5 proxy / etc.
